# Generated by Django 5.2.4 on 2025-08-31 10:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalGradeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_limit', models.PositiveIntegerField(blank=True, help_text='Maximum allowed value for midterm. Leave blank to allow any value up to 50.', null=True, verbose_name='Midterm Limit')),
                ('final_limit', models.PositiveIntegerField(blank=True, help_text='Maximum allowed value for final. Leave blank to allow any value up to 50.', null=True, verbose_name='Final Limit')),
            ],
            options={
                'verbose_name': 'Global Grade Settings',
                'verbose_name_plural': 'Global Grade Settings',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Room Number')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Building')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacity')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('credits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('tutor', 'Tutor'), ('scheduler', 'Scheduler')], max_length=10, verbose_name='Role')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('email', models.EmailField(max_length=254)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('lockout_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('students', models.ManyToManyField(blank=True, related_name='groups', to='school.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sg', models.PositiveIntegerField(blank=True, help_text='Fixed number of quizzes for this group/subject per semester. Set by teacher.', null=True, verbose_name='Number of Quizzes (SG)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='school.group')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='school.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'unique_together': {('teacher', 'group', 'subject', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacherassignment')),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(blank=True, related_name='tutors', to='school.group', verbose_name='Groups')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor Profile',
                'verbose_name_plural': 'Tutor Profiles',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
                ('week_type', models.CharField(choices=[('top', 'Top Week'), ('bottom', 'Bottom Week')], max_length=10, verbose_name='Week Type')),
                ('time_slot', models.IntegerField(choices=[(1, '8:30-9:50'), (2, '10:05-11:25'), (3, '11:40-13:00'), (4, '13:30-14:50'), (5, '15:05-16:25'), (6, '16:40-18:00')], default=1, verbose_name='Time Slot')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='school.group', verbose_name='Group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='school.room', verbose_name='Room')),
                ('scheduler', models.ForeignKey(limit_choices_to={'role': 'scheduler'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to=settings.AUTH_USER_MODEL, verbose_name='Scheduler')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_schedule_entries', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='school.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Schedule Entry',
                'verbose_name_plural': 'Schedule Entries',
                'ordering': ['week_type', 'weekday', 'time_slot'],
                'constraints': [models.UniqueConstraint(fields=('scheduler', 'weekday', 'week_type', 'time_slot', 'teacher'), name='unique_teacher_time_slot_per_scheduler'), models.UniqueConstraint(fields=('scheduler', 'weekday', 'week_type', 'time_slot', 'room'), name='unique_room_time_slot_per_scheduler')],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.IntegerField(blank=True, null=True, verbose_name='Activity')),
                ('midterm', models.IntegerField(blank=True, null=True, verbose_name='Midterm')),
                ('final', models.IntegerField(blank=True, null=True, verbose_name='Final')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total Score')),
                ('additional_scores', models.JSONField(blank=True, default=dict, null=True, verbose_name='Additional Scores')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studentprofile', verbose_name='Student')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacherassignment', verbose_name='Teacher-Subject-Group')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'unique_together': {('student', 'teacher_assignment')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('missed_lessons', models.PositiveIntegerField(default=0, help_text='Number of missed lessons', verbose_name='Missed Lessons')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studentprofile', verbose_name='Student')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacherassignment', verbose_name='Teacher-Subject-Group')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'unique_together': {('student', 'teacher_assignment', 'date')},
            },
        ),
    ]
