# Generated by Django 5.2.4 on 2025-09-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_requestlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
    ]
