# Generated by Django 5.2.4 on 2025-09-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_requestlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'LOGS'},
        ),
    ]
