# Generated by Django 5.2.4 on 2025-09-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_requestlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={},
        ),
        migrations.AddField(
            model_name='semester',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(),
        ),
    ]
