# Generated by Django 5.2.4 on 2026-04-30 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_semester_options_semester_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Request Log', 'verbose_name_plural': 'LOGS'},
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
