# Generated by Django 5.2.4 on 2026-04-30 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_requestlog_options_alter_requestlog_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Imported At')),
                ('filename', models.CharField(max_length=255, verbose_name='File Name')),
                ('sheet_name', models.CharField(max_length=100, verbose_name='Sheet Name')),
                ('rows_processed', models.IntegerField(default=0, verbose_name='Rows Processed')),
                ('rows_created', models.IntegerField(default=0, verbose_name='Rows Created')),
                ('rows_updated', models.IntegerField(default=0, verbose_name='Rows Updated')),
                ('rows_skipped', models.IntegerField(default=0, verbose_name='Rows Skipped')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='Errors')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Imported By')),
            ],
            options={
                'verbose_name': 'LMS Import Log',
                'verbose_name_plural': 'LMS Import Logs',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentExtendedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='FIN')),
                ('faculty', models.CharField(blank=True, max_length=200, null=True, verbose_name='Faculty')),
                ('specialty_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Specialty Code')),
                ('specialty_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Specialty')),
                ('education_form', models.CharField(blank=True, max_length=50, null=True, verbose_name='Education Form')),
                ('education_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Education Level')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, max_length=1, null=True, verbose_name='Gender')),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Citizenship')),
                ('birth_city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Birth City/District')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Study Status')),
                ('admission_year', models.IntegerField(blank=True, null=True, verbose_name='Admission Year')),
                ('admission_score', models.FloatField(blank=True, null=True, verbose_name='Admission Score')),
                ('study_year', models.IntegerField(blank=True, null=True, verbose_name='Study Year (Course)')),
                ('gets_scholarship', models.BooleanField(blank=True, null=True, verbose_name='Gets Scholarship')),
                ('id_card_series', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID Card Series')),
                ('id_card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Card Number')),
                ('student_card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Student Card Number')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_info', to='school.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Extended Info',
                'verbose_name_plural': 'Student Extended Info',
            },
        ),
        migrations.CreateModel(
            name='LMSGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255, verbose_name='Subject Name')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='Total Score (0-100)')),
                ('credits', models.IntegerField(default=0, verbose_name='Credits')),
                ('import_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Import Source (sheet name)')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_grades', to='school.group', verbose_name='Group')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_grades', to='school.semester', verbose_name='Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_grades', to='school.studentprofile', verbose_name='Student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_grades', to='school.subject', verbose_name='Subject (linked)')),
            ],
            options={
                'verbose_name': 'LMS Grade',
                'verbose_name_plural': 'LMS Grades',
                'ordering': ['student', 'subject_name'],
                'unique_together': {('student', 'subject_name', 'semester')},
            },
        ),
    ]
