"""
Django settings for school_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/ 

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/ 
"""

import os
from pathlib import Path
import logging
from logging.handlers import RotatingFileHandler
from celery.schedules import crontab



# settings.py
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Для Railway
if 'RAILWAY' in os.environ:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    # Для локальной разработки
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# settings.py

import environ

# Инициализируем environ
env = environ.Env()
# Прочитаем .env файл
environ.Env.read_env()

# Получаем SECRET_KEY из переменной окружения
SECRET_KEY = env('SECRET_KEY')

# DEBUG по умолчанию False в продакшене
# DEBUG = env.bool('DEBUG', False)
DEBUG = True
# DEBUG=True
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

ALLOWED_HOSTS = ['http://mbaasoiu.online','https://mbaasoiu.online','https://prod-production-85fc.up.railway.app','https://prod-production-b21c.up.railway.app','localhost','127.0.0.1','mbaasoiu.online',]











CSRF_TRUSTED_ORIGINS = [
    'https://mbaasoiu.online',
    'http://mbaasoiu.online',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://prod-production-b21c.up.railway.app',
    'https://prod-production-85fc.up.railway.app'
]
# Custom User Model
AUTH_USER_MODEL = 'school.CustomUser'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'



# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sites',
    'school',
    'django_celery_beat',
    'axes',
    'evaluation',

]

SITE_ID = 1 

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'school.middleware.RequestLoggerMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'axes.middleware.AxesMiddleware',
        'evaluation.middleware.EvaluationRequiredMiddleware',



]

ROOT_URLCONF = "school_project.urls"


AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]





AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Настройки Axes - блокировка только по IP
AXES_LOCKOUT_PARAMETERS = ['ip_address']
# Количество попыток до блокировки
AXES_FAILURE_LIMIT = 5
# Время блокировки в часах (1 час)
AXES_COOLOFF_TIME = 1
# Сообщение при блокировке
AXES_LOCKOUT_TEMPLATE = 'school/lockout.html'
# Не блокировать только по пользователю
AXES_ONLY_USER_FAILURES = False
# Сброс при успешном входе
AXES_RESET_ON_SUCCESS = True
# settings.py
SITE_NAME = 'STMS'
SITE_URL = 'https://mbaasoiu.online'
LOGIN_URL = '/login/'


if not DEBUG:
    STATIC_ROOT = BASE_DIR / 'staticfiles'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "school_project.wsgi.application"

# Database
import os


from decouple import config
import dj_database_url




DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL')  # 'DATABASE_URL' — имя переменной окружения
    )
}







# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Baku"
USE_I18N = True
USE_TZ = True






# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'












# Media files
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

MEDIA_URL = '/media/'

# Разные MEDIA_ROOT для локальной разработки и продакшна
if os.environ.get('RAILWAY_ENV'):  # если на Railway
    MEDIA_ROOT = '/app/media'
else:  # локально
    MEDIA_ROOT = BASE_DIR / 'media'  # папка media в проекте

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "sweepy.robot@gmail.com"
EMAIL_HOST_PASSWORD = "zwezrfrylbcvadhh"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ADMIN_EMAIL = "sweepy.robot@gmail.com"  # Добавлено для резервного копирования

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat Schedule - ИСПРАВЛЕНО
CELERY_BEAT_SCHEDULE = {
    'weekly-backup': {
        'task': 'school.tasks.create_weekly_backup',  # Исправлено с 'your_app' на 'school'
        'schedule': crontab(day_of_week=0, hour=2, minute=0),  # Каждое воскресенье в 2:00
    },
    'cleanup-old-backups': {
        'task': 'school.tasks.cleanup_old_backups',
        'schedule': crontab(day_of_week=1, hour=3, minute=0),  # Каждый понедельник в 3:00
    },
}

# Directories
BACKUP_DIR = BASE_DIR / 'backups'
LOGGING_DIR = BASE_DIR / 'logs'

# Create directories if they don't exist
BACKUP_DIR.mkdir(exist_ok=True)
LOGGING_DIR.mkdir(exist_ok=True)

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {module} {message} | User: {user} | IP: {ip} | URL: {url} | Data: {data}',
            'style': '{',
        },
        'simple': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
        },
    },

    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGGING_DIR / 'app.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },  # <-- здесь была ошибка, закрываем словарь file
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },

    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'school': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'school.tasks': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


